version: "3.2"
service:
  db:
    image: mongo:4.2
    container name: db
    restart: always
    ports: 
      - ${DB_PORT}:27107
    enviroment:
      MONGO_INITDB_DATABASE : ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME : ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD : ${DB_PASS}
      
